<a href="https://colab.research.google.com/github/mayatrissnawati-jpg/pm-turi2-preprocessing/blob/main/PM_P4_Maya_Trisnawati_2488010050.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np

# Dataset karyawan (sengaja mengandung masalah kualitas)
data = {
    'usia'      : [25, 32, np.nan, 45, 28, 51, 38, np.nan, 29, 41],
    'pendapatan': [4_000_000, 7_500_000, 5_200_000, 12_000_000, 4_800_000,
                   15_000_000, 8_100_000, 6_300_000, np.nan, 9_900_000],
    'pendidikan': ['SMA','S1','SMA','S2','SMA','S2','S1','S1','SMA','S2'],  # ordinal
    'kota'      : ['Bandung','Jakarta','Bandung','Surabaya','Jakarta',
                   'Surabaya','Jakarta','Bandung','Bandung','Jakarta'],    # nominal
    'membeli'   : ['Tidak','Ya','Tidak','Ya','Tidak','Ya','Ya','Tidak','Tidak','Ya']  # target
}
df = pd.DataFrame(data)
df

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2   NaN   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7   NaN   6300000.0         S1   Bandung   Tidak
8  29.0         NaN        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

In [23]:
# Langkah 1 Menangani nilai hilang (imputasi median/modus)
df['usia'] = df['usia'].fillna(df['usia'].median())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].median())
df

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2  35.0   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7  35.0   6300000.0         S1   Bandung   Tidak
8  29.0   7500000.0        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

In [26]:
# Langkah 2
X = df.drop(columns=['membeli'])
y = df['membeli']
print(X)
print(y)

   usia  pendapatan pendidikan      kota
0  25.0   4000000.0        SMA   Bandung
1  32.0   7500000.0         S1   Jakarta
2  35.0   5200000.0        SMA   Bandung
3  45.0  12000000.0         S2  Surabaya
4  28.0   4800000.0        SMA   Jakarta
5  51.0  15000000.0         S2  Surabaya
6  38.0   8100000.0         S1   Jakarta
7  35.0   6300000.0         S1   Bandung
8  29.0   7500000.0        SMA   Bandung
9  41.0   9900000.0         S2   Jakarta
0    Tidak
1       Ya
2    Tidak
3       Ya
4    Tidak
5       Ya
6       Ya
7    Tidak
8    Tidak
9       Ya
Name: membeli, dtype: object

In [27]:
# langkah 3
X['pendidikan'] = X['pendidikan'].map({'SMA':0,'S1':1,'S2':2}) # ordinal
X = pd.get_dummies(X, columns=['kota'], dtype=int) # nominal
y = y.map({'Tidak':0,'Ya':1})

print(X)
print (y)

   usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0  25.0   4000000.0           0             1             0              0
1  32.0   7500000.0           1             0             1              0
2  35.0   5200000.0           0             1             0              0
3  45.0  12000000.0           2             0             0              1
4  28.0   4800000.0           0             0             1              0
5  51.0  15000000.0           2             0             0              1
6  38.0   8100000.0           1             0             1              0
7  35.0   6300000.0           1             1             0              0
8  29.0   7500000.0           0             1             0              0
9  41.0   9900000.0           2             0             1              0
0    0
1    1
2    0
3    1
4    0
5    1
6    1
7    0
8    0
9    1
Name: membeli, dtype: int64

In [29]:
# langkah 4
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
X, y, test_size=0.3, random_state=42)

print("Jumlah data X_train:", len(X_train))
print("Jumlah data X_test :", len(X_test))
print("Jumlah data y_train:", len(y_train))
print("Jumlah data y_test :", len(y_test))

Jumlah data X_train: 7
Jumlah data X_test : 3
Jumlah data y_train: 7
Jumlah data y_test : 3

In [30]:
# Langkah 5 Membagi data (SEBELUM scaling)
from sklearn.preprocessing import StandardScaler
num = ['usia','pendapatan','pendidikan']
sc = StandardScaler()
X_train[num] = sc.fit_transform(X_train[num])
X_test[num] = sc.transform(X_test[num]) # cegah data leakage

print("X_train setelah scaling:")
print(X_train)

print("\nX_test setelah scaling:")
print(X_test)

X_train setelah scaling:
       usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0 -1.588665   -1.169416   -1.028992             1             0              0
7 -0.044130   -0.325129    0.171499             1             0              0
2 -0.044130   -0.728919   -1.028992             1             0              0
9  0.882592    0.996363    1.371989             0             1              0
4 -1.125304   -0.875751   -1.028992             0             1              0
3  1.500406    1.767234    1.371989             0             0              1
6  0.419231    0.335617    0.171499             0             1              0

X_test setelah scaling:
       usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
8 -0.970851    0.115368   -1.028992             1             0              0
1 -0.507490    0.115368    0.171499             0             1              0
5  2.427127    2.868478    1.371989             0             0              1

In [31]:
# Langkah 6 Verifikasi

print("Cek nilai hilang pada X_train:")
print(X_train.isnull().sum())

print("\nCek nilai hilang pada X_test:")
print(X_test.isnull().sum())

print("\nTipe data X_train:")
print(X_train.dtypes)

print("\nTipe data X_test:")
print(X_test.dtypes)

print("\nStatistik X_train:")
print(X_train.describe())

print("\nStatistik X_test:")
print(X_test.describe())

Cek nilai hilang pada X_train:
usia             0
pendapatan       0
pendidikan       0
kota_Bandung     0
kota_Jakarta     0
kota_Surabaya    0
dtype: int64

Cek nilai hilang pada X_test:
usia             0
pendapatan       0
pendidikan       0
kota_Bandung     0
kota_Jakarta     0
kota_Surabaya    0
dtype: int64

Tipe data X_train:
usia             float64
pendapatan       float64
pendidikan       float64
kota_Bandung       int64
kota_Jakarta       int64
kota_Surabaya      int64
dtype: object

Tipe data X_test:
usia             float64
pendapatan       float64
pendidikan       float64
kota_Bandung       int64
kota_Jakarta       int64
kota_Surabaya      int64
dtype: object

Statistik X_train:
               usia    pendapatan    pendidikan  kota_Bandung  kota_Jakarta  \
count  7.000000e+00  7.000000e+00  7.000000e+00      7.000000      7.000000
mean   1.110223e-16  1.030921e-16 -1.982541e-17      0.428571      0.428571
std    1.080123e+00  1.080123e+00  1.080123e+00      0.534522      0.534522
min   -1.588665e+00 -1.169416e+00 -1.028992e+00      0.000000      0.000000
25%   -5.847169e-01 -8.023348e-01 -1.028992e+00      0.000000      0.000000
50%   -4.412958e-02 -3.251291e-01  1.714986e-01      0.000000      0.000000
75%    6.509113e-01  6.659903e-01  7.717436e-01      1.000000      1.000000
max    1.500406e+00  1.767234e+00  1.371989e+00      1.000000      1.000000

       kota_Surabaya
count       7.000000
mean        0.142857
std         0.377964
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

Statistik X_test:
           usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  \
count  3.000000    3.000000    3.000000      3.000000      3.000000
mean   0.316262    1.033072    0.171499      0.333333      0.333333
std    1.842685    1.589508    1.200490      0.577350      0.577350
min   -0.970851    0.115368   -1.028992      0.000000      0.000000
25%   -0.739170    0.115368   -0.428746      0.000000      0.000000
50%   -0.507490    0.115368    0.171499      0.000000      0.000000
75%    0.959818    1.491923    0.771744      0.500000      0.500000
max    2.427127    2.868478    1.371989      1.000000      1.000000

       kota_Surabaya
count       3.000000
mean        0.333333
std         0.577350
min         0.000000
25%         0.000000
50%         0.000000
75%         0.500000
max         1.000000

In [41]:
# Latihan Mandiri 1

df['usia'] = df['usia'].fillna(df['usia'].mean())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].mean())

print("Mean usia:", df['usia'].mean())
print("Mean usia:", df['usia'].mean())
print("Median usia:", df['usia'].median())

Mean usia: 35.9
Mean usia: 35.9
Median usia: 35.0

In [37]:
# Latihan Mandiri 2

from sklearn.preprocessing import MinMaxScaler

scaler_minmax = MinMaxScaler()

X_train_minmax = X_train.copy()
X_test_minmax = X_test.copy()

num = ['usia', 'pendapatan', 'pendidikan']

X_train_minmax[num] = scaler_minmax.fit_transform(
    X_train_minmax[num]
)

X_test_minmax[num] = scaler_minmax.transform(
    X_test_minmax[num]
)

print("X_train setelah MinMaxScaler:")
print(X_train_minmax.describe())

print("\nX_test setelah MinMaxScaler:")
print(X_test_minmax.describe())

X_train setelah MinMaxScaler:
           usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  \
count  7.000000    7.000000    7.000000      7.000000      7.000000
mean   0.514286    0.398214    0.428571      0.428571      0.428571
std    0.349660    0.367808    0.449868      0.534522      0.534522
min    0.000000    0.000000    0.000000      0.000000      0.000000
25%    0.325000    0.125000    0.000000      0.000000      0.000000
50%    0.500000    0.287500    0.500000      0.000000      0.000000
75%    0.725000    0.625000    0.750000      1.000000      1.000000
max    1.000000    1.000000    1.000000      1.000000      1.000000

       kota_Surabaya
count       7.000000
mean        0.142857
std         0.377964
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

X_test setelah MinMaxScaler:
           usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  \
count  3.000000    3.000000        3.00      3.000000      3.000000
mean   0.616667    0.750000        0.50      0.333333      0.333333
std    0.596518    0.541266        0.50      0.577350      0.577350
min    0.200000    0.437500        0.00      0.000000      0.000000
25%    0.275000    0.437500        0.25      0.000000      0.000000
50%    0.350000    0.437500        0.50      0.000000      0.000000
75%    0.825000    0.906250        0.75      0.500000      0.500000
max    1.300000    1.375000        1.00      1.000000      1.000000

       kota_Surabaya
count       3.000000
mean        0.333333
std         0.577350
min         0.000000
25%         0.000000
50%         0.000000
75%         0.500000
max         1.000000

In [38]:
# Latihan Mandiri 3

df_latihan = df.copy()

# Menambahkan kolom kategorikal baru
df_latihan['jenis_kelamin'] = 'Laki-laki'

# Mengubah sebagian data menjadi kategori lain
df_latihan.loc[df_latihan.index[::2], 'jenis_kelamin'] = 'Perempuan'

print("Data sebelum one-hot encoding:")
print(df_latihan)

# One-hot encoding
df_latihan = pd.get_dummies(
    df_latihan,
    columns=['jenis_kelamin'],
    dtype=int
)

print("\nData setelah one-hot encoding:")
print(df_latihan)

Data sebelum one-hot encoding:
   usia  pendapatan pendidikan      kota membeli jenis_kelamin
0  25.0   4000000.0        SMA   Bandung   Tidak     Perempuan
1  32.0   7500000.0         S1   Jakarta      Ya     Laki-laki
2  35.0   5200000.0        SMA   Bandung   Tidak     Perempuan
3  45.0  12000000.0         S2  Surabaya      Ya     Laki-laki
4  28.0   4800000.0        SMA   Jakarta   Tidak     Perempuan
5  51.0  15000000.0         S2  Surabaya      Ya     Laki-laki
6  38.0   8100000.0         S1   Jakarta      Ya     Perempuan
7  35.0   6300000.0         S1   Bandung   Tidak     Laki-laki
8  29.0   7500000.0        SMA   Bandung   Tidak     Perempuan
9  41.0   9900000.0         S2   Jakarta      Ya     Laki-laki

Data setelah one-hot encoding:
   usia  pendapatan pendidikan      kota membeli  jenis_kelamin_Laki-laki  \
0  25.0   4000000.0        SMA   Bandung   Tidak                        0
1  32.0   7500000.0         S1   Jakarta      Ya                        1
2  35.0   5200000.0        SMA   Bandung   Tidak                        0
3  45.0  12000000.0         S2  Surabaya      Ya                        1
4  28.0   4800000.0        SMA   Jakarta   Tidak                        0
5  51.0  15000000.0         S2  Surabaya      Ya                        1
6  38.0   8100000.0         S1   Jakarta      Ya                        0
7  35.0   6300000.0         S1   Bandung   Tidak                        1
8  29.0   7500000.0        SMA   Bandung   Tidak                        0
9  41.0   9900000.0         S2   Jakarta      Ya                        1

   jenis_kelamin_Perempuan
0                        1
1                        0
2                        1
3                        0
4                        1
5                        0
6                        1
7                        0
8                        1
9                        0

# Latihan Mandiri 4
Pada data latih menggunakan fit_transform karena scaler perlu mempelajari nilai atau parameter dari data latih sekaligus melakukan transformasi, sedangkan data uji menggunakan transform karena data uji tidak boleh digunakan untuk mempelajari parameter scaling, karena untuk mencegah terjadinya data leakage

E. Refleksi
1. Karena data harus dibagi menjadi data latih dan data uji terlebih dahulu sebelum dilakukan scaling, karena scaling dilakukan dengan fit pada data latih saja, kemudian data uji hanya dilakukan transform, karena untuk mencegah terjadinya data leakage
2. Label econding digunakan ketika data kategorikal dapat direpresentasikan  dalam bentuk urutan atau nilai angka, seperti pendidikan SMA,S1, dan S2. Sedangkan one-hot encoding digunakan untuk data kategorikal nominal seperti kota, yang tidak memiliki utrutan tertentu
3. Normalisasi digunakan untuk mengubah nilai fitur ke rentang tertentu, sedangkan standardisasi mengubah data berdasarkan rata-rata dan standar deviasi sehingga skala data menjadi lebih seragam